package exceptions;

public class ExceptionTes extends ExceptionTest {

	public static void main(String[] args)  {
		
		System.out.println("Demonstrando RunTimeException");
	}
}
		
		// tratamento de multiplas excessões
		// RunTimeException
		/*
		try {
			throw new IndexOutOfBoundsException();			
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Dentro do throws ArrayIndexOutOfBoundsException");	
		}catch(IndexOutOfBoundsException e) {
			System.out.println("Dentro do RunTimeException");
		}catch(IllegalArgumentException e) {
			System.out.println("dentro do IllegalArgumentExcepition");
		}catch (ArithmeticException e) {
			System.out.println("Dentro do AtithmeticExcepition");
		}
		System.out.println("finalm de programa");
	}
	*/

